version: "3"
services:
  bot-service:
    build: .
    ports:
      - 5000:5000
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.1'
    #      memory: 500M
    entrypoint: ["bash", "-c", "python app.py"]